#!/bin/bash

# Liste des répertoires à exclure
exclude_dirs=("libs/deps" "build")

# Récupérer la liste des fichiers à valider
files_to_format=$(git diff --cached --name-only | grep -E '\.cpp$|\.hpp$')

# Supprimer les fichiers supprimés de la zone de staging
for deleted_file in $(git diff --cached --name-only --diff-filter=D | grep -E '\.cpp$|\.hpp$'); do
    git rm --cached "$deleted_file"
done

# Formater les fichiers
for file in $files_to_format; do
    exclude=false

    # Vérifie si le fichier se trouve dans un répertoire exclu
    for dir in "${exclude_dirs[@]}"; do
        if [[ "$file" == *"$dir"* ]]; then
            exclude=true
            break
        fi
    done

    # Si le fichier n'est pas exclu, existe sur le système de fichiers et n'est pas un dossier, exécute clang-format
    if [ "$exclude" = false ] && [ -e "$file" ] && [ ! -d "$file" ]; then
        clang-format -i "$file"
        echo "Formatted $file"
    fi
done
