repos:
  -   repo: local
      hooks:
        -   id: custom-clang-format
            name: Custom Clang-Format
            entry: ./.cl-format.sh
            language: system
            types: [file]
