name: Windows compiling action

on:
  pull_request:
    branches:
      - main

jobs:
  compile_project:
    name: "Test that the project compile as expected"
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Configure the project using cmake"
        run: "cmake -Bbuild -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE='.\\cmake\\windows-base.cmake'"
      - name: "Compile the code"
        run: "cmake --build build --config=Release"
      - name: "Run unit tests"
        working-directory: build/tests
        run: "ctest -C Release"
