name: Compiling action

on:
  pull_request:
    branches:
      - main

jobs:
  compile_project:
    name: "Test that the project compile as expected"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Install dependencies"
        run: |
          sudo apt update
          sudo apt install \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libudev-dev \
          libxi-dev \
          libfreetype-dev \
          libopenal-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev

      - name: "Configure the project using cmake"
        run: "cmake -Bbuild --preset linux-amd64"
      - name: "Compile the code"
        run: "cmake --build build"
      - name: "Run unit tests"
        run: "cd build/tests; ctest"
