name: Windows compiling action

on:
  pull_request:
    branches:
      - main

jobs:
  compile_project:
    name: "Test that the project compile as expected"
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Install dependencies"
        run: choco install ninja cmake visualstudio2022buildtools
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: "Configure the project using cmake"
        run: "cmake -Bbuild --preset x64-release"
      - name: "Compile the code"
        run: "cmake --build build"
