name: 🚀 Release me

on:
  workflow_call:

jobs:
  create_release:
    name: "Create release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: windows-installer
          path: "./generated_packages/"

      - uses: actions/download-artifact@master
        with:
          name: linux-installer
          path: "./generated_packages/"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./generated_packages/R-Type-${{  github.ref_name }}-win64.exe, ./generated_packages/R-Type-${{  github.ref_name }}-Linux.sh"
          generateReleaseNotes: true
          tag: "v${{  github.ref_name }}-stable"
